version: '3.8'

services:
  eventstore:
    image: eventstore/eventstore:24.2.0-alpha-arm64v8
    container_name: eventstore
    deploy:
      mode: replicated
      replicas: 1
    environment:
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INT_TCP_PORT: 1112
      EVENTSTORE_DB: /var/lib/eventstore
      EVENTSTORE_LOG: /var/log/eventstore
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: true
      EVENTSTORE_NODE_IP: '0.0.0.0'
      EVENTSTORE_REPLICATION_IP: '0.0.0.0'
      EVENTSTORE_INSECURE: true
    ports:
      - '2113:2113'
      - '1113:1113'
    volumes:
      - eventstore-data:/var/lib/eventstore
      - eventstore-logs:/var/log/eventstore

  postgres:
    image: postgres:15
    container_name: postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  eventstore-data:
  eventstore-logs:
  postgres-data:
